name: "🛸 Compile Saucer"
description: "Installs Dependencies & Compiles Saucer"

inputs:
  backend:
    required: true
    description: The backend to use

  platform:
    required: true
    description: The platform which is used to compile

  cmake-args:
    description: Additional Arguments passed to cmake

  build-type:
    required: true
    description: The CMake build configuration

  install:
    required: false
    description: Whether or not to build install target

runs:
  using: "composite"
  steps:
    - name: 📋 Install Base Dependencies
      shell: bash
      if: inputs.platform == 'Linux'
      run: "pacman --noconfirm -Syu cmake gcc git xorg-server-xvfb xorg-xwd openssh tmate"

    - name: 📋 Install Qt5-Dependencies
      shell: bash
      if: inputs.backend == 'Qt5'
      run: "pacman --noconfirm -Syu qt5-base qt5-webchannel qt5-webengine"

    - name: 📋 Install Qt6-Dependencies
      shell: bash
      if: inputs.backend == 'Qt6'
      run: "pacman --noconfirm -Syu qt6-base qt6-declarative qt6-svg qt6-tools qt6-translations qt6-webchannel qt6-webengine"

    - name: 📋 Install WebKitGtk-Dependencies
      shell: bash
      if: inputs.backend == 'WebKitGtk'
      run: "pacman --noconfirm -Syu gtk4 libadwaita webkitgtk-6.0"

    - name: 🔨 Compile
      shell: bash
      run: |
        cmake -B build -Dsaucer_backend=${{ inputs.backend }} ${{ inputs.cmake-args }}
        cmake --build build --config ${{ inputs.build-type }}

    - name: 📥 Install
      shell: bash
      if: inputs.install == 'true'
      run: "cmake --install build --prefix 'artifact' --config ${{ matrix.config }}"
