#![feature(vec_into_raw_parts)]
#![feature(mpmc_channel)]
#![feature(macro_metavar_expr_concat)]
// Names generated by bindgen will preserve the original name in the C API.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
// Macros defined in this crate are meant to be used in unsafe context, making it unnecessary to require unsafe blocks
// to be listed explicitly.
#![allow(clippy::macro_metavars_in_unsafe)]
// Unsafe APIs are only used internally.
#![allow(clippy::missing_safety_doc)]
// Functional APIs are used excessively for cleanups and event handling.
// They do can lead to complex types, but should not generally affect readability.
#![allow(clippy::type_complexity)]

pub mod app;
mod capi;
pub mod collector;
pub mod embed;
pub mod icon;
mod macros;
pub mod navigation;
pub mod options;
pub mod prefs;
pub mod scheme;
pub mod script;
pub mod stash;
pub mod webview;
