name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.os == 'ubuntu-latest' && 'archlinux:base-devel' || '' }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo pacman --noconfirm -Syu cmake clang lld git gtk4 libadwaita webkitgtk-6.0 xorg-server-xvfb

      - name: Build
        run: cargo build --verbose

      - name: Test
        if: matrix.os == 'ubuntu-latest'
        timeout-minutes: 5
        run: |-
          eval $(dbus-launch --sh-syntax --exit-with-session)
          export WEBKIT_DISABLE_SANDBOX_THIS_IS_DANGEROUS=1
          xvfb-run cargo test --verbose --test '*'

      - name: Test
        if: matrix.os == 'windows-latest'
        timeout-minutes: 5
        run: cargo test --verbose --test '*'

      - name: Test
        if: matrix.os == 'macos-latest'
        timeout-minutes: 5
        run: |-
          cargo run --bin app-test-exec
          cargo run --bin webview-test-exec  
