name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install libwebkitgtk-6.0-4 libwebkitgtk-6.0-dev libadwaita-1-dev

      - uses: egor-tensin/setup-gcc@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          version: 14

      - name: Build
        run: cargo build --verbose

      - name: Test
        if: matrix.os == 'ubuntu-latest'
        timeout-minutes: 2
        uses: coactions/setup-xvfb@v1
        with:
          run: cargo test --verbose

      - name: Test
        if: matrix.os == 'windows-latest'
        timeout-minutes: 2
        run: cargo test --verbose

      - name: Test
        if: matrix.os == 'macos-latest'
        timeout-minutes: 2
        run: |-
          cargo run --bin app-test-exec
          cargo run --bin webview-test-exec  
